run:
  name: "qwen2.5_1.5b_run_on_humaneval_x86_to_arm64"
  timestamp: null 
  save_artifacts_path: "artifacts/"
  
# Model Configuration
model:
  name: "qwen:ahmedheakl/ex19_qwen2.5-1.5b-1M-stack-16kcw"
  is_enc_dec: false
  checkpoint: "..." 
  max_length: 4096

# Inference Configuration
inference:
  beam_size: 50
  temperature: 0.7
  k: 20
  num_guesses: 50
  lambda_val: 0.95

# Language Configuration
language:
  source_lang: "x86"
  target_lang: "arm64"
  viceversa: false

# Data Configuration
dataset:
  name: "bringup"
  gcc_args: "..."
  additional_notes: "..."

# Feature Flags
features:
  guess: false
  sketch: false
  few_shot: false
  verbose: false
  log_attention_maps: true

# Sketch Configuration
sketch:
  template_path: "scratch_sketch.rkt"
  view_uncertain: ""
